export const SUGGESTION_ADD = 'SUGGESTION_ADD';
export const SUGGESTION_ADD_ERROR = 'SUGGESTION_ADD_ERROR';
export const SUGGESTION_DATA_LOADED = 'SUGGESTION_DATA_LOADED';
export const SUGGESTION_SORTED_DATA_LOADED = 'SUGGESTION_SORTED_DATA_LOADED';


export const SORTIE_ADD = 'SORTIE_ADD';
export const SORTIE_ADD_ERROR = 'SORTIE_ADD_ERROR';
export const SORTIE_DATA_LOADED = 'SORTIE_DATA_LOADED';
export const SORTIE_NEXT_DATA_LOADED = 'SORTIE_NEXT_DATA_LOADED';
export const SORTIE_SUSCRIBED = 'SORTIE_SUSCRIBED';
export const SORTIE_SUSCRIBED_LIST = 'SORTIE_SUSCRIBED_LIST';
export const SORTIE_DELETE = 'SORTIE_DELETE';
export const SORTIE_DELETE_ERROR = 'SORTIE_DELETE_ERROR';


export const USER_ADD = 'USER_ADD';
export const USER_ADD_ERROR = 'USER_ADD_ERROR';
export const USER_DATA_LOADED = 'USER_DATA_LOADED';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_CONNECT_ERROR = 'USER_CONNECT_ERROR';


export const CONNEXION_TEST = 'CONNEXION_TEST';
export const CONNEXION_TEST_ERROR = 'CONNEXION_TEST_ERROR';
export const CONNEXION_DATA_LOADED = 'CONNEXION_DATA_LOADED';


export const TODO_OBJECT_ADD = 'TODO_OBJECT_ADD';
export const TODO_OBJECT_ADD_ERROR = 'TODO_OBJECT_ADD_ERROR';
export const TODO_OBJECT_DATA_LOADED = 'TODO_OBJECT_DATA_LOADED';

export const EVENEMENT_ADD = 'EVENEMENT_ADD';
export const EVENEMENT_ADD_ERROR = 'EVENEMENT_ADD_ERROR';
export const EVENEMENT_DATA_LOADED = 'EVENEMENT_DATA_LOADED';
export const EVENEMENT_NOTSEEN_DATA_LOADED = 'EVENEMENT_NOTSEEN_DATA_LOADED';

export const THREAD_ADD = 'THREAD_ADD';
export const THREAD_ADD_ERROR = 'THREAD_ADD_ERROR';
export const THREAD_DATA_LOADED = 'THREAD_DATA_LOADED';

export const MESSAGE_ADD = 'MESSAGE_ADD';
export const MESSAGE_ADD_ERROR = 'MESSAGE_ADD_ERROR';
export const MESSAGE_DATA_LOADED = 'MESSAGE_DATA_LOADED';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const REDIRECT = 'REDIRECT';