export const SUGGESTION_ADD = 'SUGGESTION_ADD';
export const SUGGESTION_ADD_ERROR = 'SUGGESTION_ADD_ERROR';
export const SUGGESTION_DATA_LOADED = 'SUGGESTION_DATA_LOADED';

export const SORTIE_ADD = 'SORTIE_ADD';
export const SORTIE_ADD_ERROR = 'SORTIE_ADD_ERROR';
export const SORTIE_DATA_LOADED = 'SORTIE_DATA_LOADED';

export const USER_ADD = 'USER_ADD';
export const USER_ADD_ERROR = 'USER_ADD_ERROR';
export const USER_DATA_LOADED = 'USER_DATA_LOADED';

export const CONNEXION_TEST = 'CONNEXION_TEST';
export const CONNEXION_TEST_ERROR = 'CONNEXION_TEST_ERROR';
export const CONNEXION_DATA_LOADED = 'CONNEXION_DATA_LOADED';
